[package]
edition = "2021"
name    = "affine_pdf"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# pdfium-render = "0.8" 
pdfium-render = { git = "https://github.com/fundon/pdfium-render", branch = "msrv-1.63" }
chrono        = { workspace = true }
anyhow        = { workspace = true }
napi          = { workspace = true }
napi-derive   = { workspace = true }
notify        = { workspace = true, features = ["serde"] }
serde         = { workspace = true }
serde_json    = { workspace = true }
tokio         = { workspace = true, features = ["full"] }

[build-dependencies]
napi-build    = { workspace = true }
anyhow        = { workspace = true }
tokio         = { workspace = true, features = ["full"] }

reqwest       = "0.12"
tar           = "0.4"
flate2        = "1.0"
